[package]
name = "pact_ex"
version = "0.1.0"
authors = []
edition = "2021"
license = "MIT"

[lib]
name = "pact_ex"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pact_ffi = "0.4.23"
pact_models = "1.2.4"
rustler = "0.35"
